$ErrorActionPreference = 'Stop'

$requiredDirs = @(
  'cap4k-authoring',
  'cap4k-business-discovery',
  'cap4k-tactical-modeling',
  'cap4k-technical-design',
  'cap4k-generator-inputs',
  'cap4k-generation-review',
  'cap4k-handwritten-implementation',
  'cap4k-verification-audit',
  'cap4k-service-integration',
  'shared',
  'scripts'
)

$forbiddenDirs = @(
  'cap4k-modeling',
  'cap4k-generation',
  'cap4k-generated-output-review',
  'cap4k-implementation',
  'cap4k-verification'
)

foreach ($dir in $requiredDirs) {
  $path = Join-Path 'skills' $dir
  if (-not (Test-Path -LiteralPath $path -PathType Container)) {
    throw "Missing required cap4k skill directory: $path"
  }
}

foreach ($dir in $forbiddenDirs) {
  $path = Join-Path 'skills' $dir
  if (Test-Path -LiteralPath $path -PathType Container) {
    throw "Forbidden removed skill directory still exists: $path"
  }
}

$focusedSkillDirs = Get-ChildItem -LiteralPath 'skills' -Directory |
  Where-Object { $_.Name -notin @('scripts', 'shared') }

if ($focusedSkillDirs.Count -lt 9) {
  throw "Expected at least 9 focused cap4k skill directories, found $($focusedSkillDirs.Count)."
}

foreach ($dir in $focusedSkillDirs) {
  $skillFile = Join-Path $dir.FullName 'SKILL.md'
  if (-not (Test-Path -LiteralPath $skillFile -PathType Leaf)) {
    throw "Missing SKILL.md in focused skill directory: $($dir.FullName)"
  }
}

$requiredSharedPaths = @(
  'skills/shared/rules/cap4k-positioning.md',
  'skills/shared/rules/generated-skeleton-ownership.md',
  'skills/shared/rules/generator-input-source-of-truth.md',
  'skills/shared/rules/layer-and-runtime-boundaries.md',
  'skills/shared/rules/naming-layout-and-testing.md',
  'skills/shared/rules/verification-claim-policy.md',
  'skills/shared/workflows/forced-rollback.md',
  'skills/shared/workflows/skeleton-generation-gate.md',
  'skills/shared/references/tactical-affordance-map.md',
  'skills/shared/references/generator-supported-skeletons.md',
  'skills/shared/references/output-ownership-taxonomy.md',
  'skills/shared/references/runtime-capability-map.md'
)

$missingSharedPaths = $requiredSharedPaths |
  Where-Object { -not (Test-Path -LiteralPath $_ -PathType Leaf) }

if ($missingSharedPaths.Count -gt 0) {
  throw "Missing shared cap4k skill files: $($missingSharedPaths -join ', ')"
}

$sharedCoreText = $requiredSharedPaths |
  Where-Object { $_ -like 'skills/shared/rules/*' -or $_ -like 'skills/shared/workflows/*' } |
  ForEach-Object { Get-Content -LiteralPath $_ -Raw }
$sharedCoreCombined = $sharedCoreText -join "`n"

$requiredSharedCorePatterns = @(
  'DDD tactical framework plus generator-backed authoring system',
  'Treat cap4k skeletons as generated by cap4k',
  'HTTP and message transport handle consume, parse, register, and dispatch',
  'Treat plan.json as generated evidence',
  'Make role inferable from file name plus directory',
  'Match every claim to its evidence mode'
)

foreach ($pattern in $requiredSharedCorePatterns) {
  if (-not $sharedCoreCombined.Contains($pattern)) {
    throw "Missing required shared core wording: $pattern"
  }
}